Repository gxxrxn/coffee-tech-seminar, pull requests merged in 2022-05, with the labels that each got.

#1 Header 컴포넌트 구현
  src/components/Header.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/img/team_coffee_logo.png
Labels: develop

#2 About 컴포넌트 구현
  src/components/About/About.css
  src/components/About/About.js
  src/components/About/img/circle.png
  src/components/About/img/js.png
  src/components/About/img/react.png
  src/components/About/img/ts.png
Labels: enhancement, develop

#3 fix: header z-index 설정
  src/App.js
  src/components/About/About.css
  src/components/Header/Header.css
Labels: bug

#4 Notice 컴포넌트 구현
  package-lock.json
  src/App.css
  src/App.js
  src/components/Notice/Notice.css
  src/components/Notice/Notice.js
Labels: develop

#5 Session 컴포넌트 구현
  src/App.css
  src/App.js
  src/components/About/About.css
  src/components/About/About.js
  src/components/Header/Header.css
  src/components/Session/Session.css
  src/components/Session/Session.js
  src/components/Session/img/youtube_link.png
Labels: enhancement, develop

#7 Notice 컴포넌트 구현
  src/components/Notice/Notice.css
  src/components/Notice/Notice.js
  src/components/Notice/img/arrow.png
  src/components/Notice/img/background.png
  src/components/Notice/img/econo_logo.png
  src/components/Notice/img/github_logo.png
  src/components/Notice/img/medium_logo.png
Labels: develop

#11 Header 버그 수정 및 CSS 개선
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/NavList.js
  src/components/Header/img/hamburger_icon.png
Labels: develop
